### ISSUE TITLE
[IgbInput] Support @bind-Value:event syntax

### ISSUE THREAD

**Issue by brianlagunas** [IgniteUI/igniteui-blazor#1]
When using the default input in Blazor, you can specify an event in which to update the binding.

For example:
```
<h1>Greetings, @userName</h1>

<input @bind-value="userName" @bind-value:event="oninput" />

@code {
    string userName = "Bradley";
}
```

Results in:
![blazor-data-binding1-min](https://user-images.githubusercontent.com/835562/151588209-81ae7a10-0dcd-4c17-b72e-56e0720e5454.gif)

This allows the developer to update the binding each time a new character is entered into the input.

I tried a similar appraoch using the following syntax:
```
<IgbInput @bind-Value="myValue" @bind-Value:event="InputOcurred"></IgbInput>
```
But this fails with a compile error:

"Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 2: cannot convert from 'Microsoft.AspNetCore.Components.EventCallback<string>' to 'Microsoft.AspNetCore.Components.EventCallback'	UntitledApp	C:\Users\brian\Downloads\untitled-app\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Pages_MasterView_razor.g.cs	121	Active"

We need to add this feature to the IgbInput

**Comment by brianlagunas** [comment]
As a work-around you can do this:

```html
 <IgbInput @ref="input" Value="@myValue" @oninput="(async (e) => myValue = await input.GetCurrentValueAsync())"></IgbInput>
```

```cs
    IgbInput input;
    string myValue = "Hello world";
```

**Comment by gmurray81** [comment]
this is resolved
