### ISSUE TITLE
Snackbar Action event doesn't fire; cannot close notification

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-blazor#10]
`
@using IgniteUI.Blazor.Controls
@inject IIgniteUIBlazor IgniteUIBlazor

<div class="container sample vertical">

    <div class="button-container">

        <IgbButton onclick="snackbar1.show()">Show Snackbar</IgbButton> 
        <IgbButton onclick="snackbar1.hide()">Hide Snackbar</IgbButton> 

        <IgbSnackbar @ref="ToggleSnackbarRef" id="snackbar1" KeepOpen="true" ActionText="Close" Action=OnActionClick> @SnackbarDisplayText </IgbSnackbar>
    </div>
</div>

@code {

    public string SnackbarDisplayText { get; set; } = "Hello there!";

    private IgbSnackbar snackbar1;

    public IgbSnackbar ToggleSnackbarRef
    {
        get { return snackbar1; }
        set { 
            snackbar1 = value; 
            StateHasChanged();
        }
    }

    protected override void OnInitialized()
    {   
        IgbCheckboxModule.Register(IgniteUIBlazor);
        IgbButtonModule.Register(IgniteUIBlazor);
        IgbSnackbarModule.Register(IgniteUIBlazor);
    }

    private void OnActionClick(IgbVoidEventArgs e)
    {
        this.ToggleSnackbarRef.Hide();
    }
}
`

**Comment by agoldenbaum** [comment]
Verified that the Action event is firing correctly now. Marking this closed.
