### ISSUE TITLE
Two-way binding now working for rating

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-blazor#110]
## Description  
I have a rating component bound to a variable via `@bind`.

## Steps to reproduce  
Use code like this:
```razor
<IgbRating @bind-Value="_rating"></IgbRating>
<p>Rating is @_rating</p>
...
@code {
    private double _rating;
}
```

## Result  
Changing the value of the rating does not update the bound variable.

## Expected result  
Rating component should update the related bound variable. Note when using `Change` event it is working:
```razor
<IgbCalendar Value="_date" Change="@(e => _date = (DateTime)e.Detail)"></IgbCalendar>
```
This one works fine.

**Comment by gmurray81** [comment]
@wnvko @zdrawku 
note: what the generation requires to work this out is this provided on the value property:

 /* @tsTwoWayProperty(true, "igcChange", "detail", false) */

this means that when igcChange is fired, we will look at the detail property on the custom event and propagate that outward to act as the new Value at the blazor level. This should also cause the ValueChanged event to be synthesized which is the other required part for the two way bind to work.

**Comment by gmurray81** [comment]
I am seeing that attribute in place for rating, so either something messed with the generation, or perhaps there was something wrong with the testing methodology and this is working?

**Comment by gmurray81** [comment]
Are there more parameters for how this was being tested? I essentially just tried the above and it seems to work fine to me.

**Comment by wnvko** [comment]
@gmurray81 
This is my code, it is really simple:
```razor
<IgbRating @bind-Value="_rating"></IgbRating>
<IgbRating Value="_rating" Change="@(e => _rating = e.Detail)"></IgbRating>
<p>Rating is @_rating</p>
...
@code {
    private double _rating;
}
```
Note, if I set `_rating` variable to some value both ratings above initialize correctly with the provided value. Only `@bind` does not update the bound variable. I am using version 23.2.204.

**Comment by wnvko** [comment]
Here is the repo where I have the projects I am testing the two-way data banding - https://github.com/wnvko/two-way-binding
Get it and open the Blazor folder. Inside is the Blazor project which is not working correctly.

**Comment by wnvko** [comment]
@gmurray81 
After restarting my VS and removing the bin/obj folder by hand it is working at my side now. Probably some bad caching :(

Closing this issue now.

Thank you for your time.
