### ISSUE TITLE
Components render as normal html elements instead of IgniteUI for Blazor controls when using Blazor WebApp template with .NET 8

### ISSUE THREAD

**Issue by IvanKitanov17** [IgniteUI/igniteui-blazor#114]
## Description  
Components render as normal html elements instead of IgniteUI for Blazor controls when using Blazor WebApp template with .NET 8

Since the Blazor WebApp template has different file structure, the issue might be caused from this.

The following [issue ](https://github.com/dotnet/aspnetcore/issues/53008) might be connected.

## Steps to reproduce  

 Run the attached sample

## Result  
When the page loads the card component should be present, however only native html elements are present.

## Expected result  
The IgniteUI for Blazor comonents should render correctly.

## Attachments  
[Sample.zip](https://github.com/IgniteUI/igniteui-blazor/files/15150428/Sample.zip)

**Comment by mddifilippo89** [comment]
Please update your HeadOulet and Routes with the following to get this working

    <HeadOutlet @rendermode="@InteractiveServer" />
    <Routes @rendermode="@InteractiveServer" />

**Comment by mddifilippo89** [comment]
@IvanKitanov17 
I also assigned myself work item 31163. If my suggestion fixes the issue for you we can close that too.

**Comment by IvanKitanov17** [comment]
@mddifilippo89
It resolves the issue, thank you for the clarification!

**Comment by danielgooderidge** [comment]
This resolved my issue.

Is this a workaround or a permanent fix going forward for .net 8.0 and later versions?
