### ISSUE TITLE
Breaking Change - IgbPivotConfiguration

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-blazor#122]
![image](https://github.com/IgniteUI/igniteui-blazor/assets/17785923/24da07c4-3ce6-4c7d-a00b-ed821471d273)

**Comment by mddifilippo89** [comment]
@dkamburov

**Comment by dkamburov** [comment]
https://github.com/IgniteUI/igniteui-xplat-docs/pull/1319/files#diff-530e645e74c886b73e2d11b7de840792697b907a462716867f65ee89865f59ddR20

**Comment by mddifilippo89** [comment]
@dkamburov This can be closed? 

eg.
var pivotDimension2 = new IgbPivotDimension();
pivotConfiguration1.Rows = [pivotDimension2,pivotDimension3];

**Comment by dkamburov** [comment]
Yeah
