### ISSUE TITLE
IgbPivotGrid - not loading properly

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-blazor#134]
Created from this found issue:
https://github.com/IgniteUI/igniteui-webcomponents/issues/1368

Although with Blazor I get a few different behaviors with the configuration depending on the following:

1. With no config 
![image](https://github.com/user-attachments/assets/ede0c68d-252d-48d6-a6ca-55bf137a7eb0)
2. With AutoGenerateConfig
![image](https://github.com/user-attachments/assets/2dc0b1b3-1313-4679-b488-dbaa77da6370)
3. With PivotConfiguration set
The pivotgrid is missing
![image](https://github.com/user-attachments/assets/d74673ae-064b-4061-9e4d-f4c757111c6f)

**Comment by mddifilippo89** [comment]
[features.zip](https://github.com/user-attachments/files/16800114/features.zip)

**Comment by MayaKirova** [comment]
Is also related to this one: https://github.com/IgniteUI/igniteui-angular/issues/14705
Should be fixed once PRs in angular are merged and new version is tagged.

**Comment by mddifilippo89** [comment]
@damyanpetev @MayaKirova 

The pivot doesn't appear to be missing when assigning a Configuration however I am seeing no data in Blazor Server and an error in the console

Cannot read properties of undefined (reading 'headerGroupClasses')

![image](https://github.com/user-attachments/assets/ea7bff68-b94e-465f-a089-8b8ad7ce2b63)

[BlazorServerPivot.zip](https://github.com/user-attachments/files/16909377/BlazorServerPivot.zip)

**Comment by mddifilippo89** [comment]
[BlazorServerPivot_Working_Old_version.zip](https://github.com/user-attachments/files/16909572/BlazorServerPivot_Working_Old_version.zip)
I attached a working version of the sample. (23.2.120)

The only noticeable difference is how the configuration components like Rows, Columns, Filters etc were a collection

**Comment by mddifilippo89** [comment]
Here is new sample WASM sample but with the same code using 24.1.43. I only get 1 row to show up and no row configurations.

[BlazorApp30.zip](https://github.com/user-attachments/files/16909867/BlazorApp30.zip)

**Comment by MayaKirova** [comment]
@mddifilippo89 It seems that the row dimension is not enabled in the samples, so it does not show. 
It shows correctly after setting:
```
 pivotDimension3.Enabled = true;
```
I've noticed that this is also the case in this sample here: https://staging.infragistics.com/blazor-client/grids/pivot-grid/data-selector

So I've updated the sample so it renders correctly: https://github.com/IgniteUI/igniteui-blazor-examples/pull/813

**Comment by mddifilippo89** [comment]
Is this a breaking change?

**Comment by mddifilippo89** [comment]
In version 23.1.120:

![image](https://github.com/user-attachments/assets/18ab9b2d-2600-4c24-9a12-72398f677098)

**Comment by MayaKirova** [comment]
@mddifilippo89 
Make sure also not to mix both of these:
```
                      AutoGenerateConfig=true
                      PivotConfiguration="PivotConfiguration"
```
It should either be autogenerated or it should use the set config.

**Comment by dkamburov** [comment]
Please re-open if there are additional questions on this one.
