### ISSUE TITLE
Disabled date picker allows value clearing

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-blazor#2]
1. Add `IgcDatePicker`.
2. Set `IsDisabled` to true.
3. Run the application.
4. Click on clear icon.
The value of the date picker is cleared which is not correct. The value should not be cleared as the picker is disabled.

**Comment by mddifilippo89** [comment]
I can reproduce this and is a bug

**Comment by mddifilippo89** [comment]
I am logging a TFS work item for our team to review and fix

**Comment by brianlagunas** [comment]
This has been fixed. Thanks for reporting it
