### ISSUE TITLE
Accordin SingleSelect does not work properly

### ISSUE THREAD

**Issue by PlamenaMiteva** [IgniteUI/igniteui-blazor#24]
## Steps to reproduce  

Add an accordion to the page and set SingleSelection to true. Open the first panel, then open the second one.

## Result  
The first panel remains opened

## Expected result  
Should close the previously opened panel.

Note: I am testing this with the latest dev nugget package 22.1.602-dev

**Comment by Lipata** [comment]
Already fixed
