### ISSUE TITLE
Calendar does not display selected date when value is not set

### ISSUE THREAD

**Issue by PlamenaMiteva** [IgniteUI/igniteui-blazor#27]
## Steps to reproduce  
Add a calendar to the page

## Result  
The selected date in the header displays "Selected date"

## Expected result  
The selected date in the header  should display the current date

## Attachments  
![calendar_selected_date](https://user-images.githubusercontent.com/10612538/183938463-5c468dcc-94f9-41c2-8e55-e8df462b7815.jpg)

**Comment by dafo** [comment]
This is logged for WebComponents and should be fixed there - https://github.com/IgniteUI/igniteui-webcomponents/issues/694
