### ISSUE TITLE
Missing Grid Layout Save and Load

### ISSUE THREAD

**Issue by JoeCSolomon** [IgniteUI/igniteui-blazor#42]
The last version of the Blazor grid had functionality to save and load the layout such as filtering, sorting and etc. The IgbGrid doesn't seem to support this. Since my current app uses this, I am taking away functionality from the users by upgrading.

**Comment by jbarraathena** [comment]
Hi, 

Is there any ETA on this feature. Is kind of critical for the implementation we are doing and using the old version it is not an opcion due there are feaures of it that are also necessary. Is there any way to do this? maybe with Javascript saving the localstorage manually or something similar?

Thanks.

**Comment by mddifilippo89** [comment]
https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/grid/state-persistence
