### ISSUE TITLE
Slider tick label orientation

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-blazor#5]
Having these two sliders:
```
<IgbSlider
	PrimaryTicks=3
	SecondaryTicks=2
	HideSecondaryLabels=true
	TickOrientation=SliderBaseTickOrientation.Start
	TickLabelRotation=TickLabelRotation.Ninety
></IgbSlider>
```
and
```
<IgbSlider
	PrimaryTicks=3
	SecondaryTicks=2
	HideSecondaryLabels=true
	TickOrientation=SliderBaseTickOrientation.Start
	TickLabelRotation=TickLabelRotation.NegativeNinety
></IgbSlider>
```
both draws tick labels rotated in same direction
![image](https://user-images.githubusercontent.com/5990334/162168639-de51a6a1-02e5-48e5-a91d-386b4c583d85.png)

Second slider's tick labels should be like this:
![image](https://user-images.githubusercontent.com/5990334/162169363-1efa6591-9119-41c5-91c1-b244a3734449.png)

**Comment by mddifilippo89** [comment]
TFS item 273996 was created.

**Comment by gmurray81** [comment]
this is resolved
