### ISSUE TITLE
Cannot bind combo to array of strings

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-blazor#65]
## Description  
I am trying to bind IgbCombo to an array of strings as described in the node [here](https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/inputs/combo/overview#data-value-and-display-properties)

## Steps to reproduce  

1. Add IgbCombo component.
2. Set `data` to an array of strings.
3. Run the application and drop down the combo

## Result  
All the values of the combo are shown as `[object Object]`.

## Expected result  
Combo should show the strings from the passed data.

## Attachments  
![image](https://github.com/IgniteUI/igniteui-blazor/assets/5990334/e08691ed-7e7b-4a60-b796-3f4bd8bba804)

**Comment by dkamburov** [comment]
[comboCollection.zip](https://github.com/user-attachments/files/17475794/comboCollection.zip)
attaching working example with the latest version
