### ISSUE TITLE
IgbCombo does not expose a Change event or Value property at the Blazor level

### ISSUE THREAD

**Issue by agoldenbaum** [IgniteUI/igniteui-blazor#76]
The IgbCombo does not expose a Change event or Value property at the .razor level. This makes the component rather difficult to use at the Blazor level, as much of its basic functionality **requires** the usage of JavaScript to use.

**Comment by agoldenbaum** [comment]
This is now exposed.

**Comment by SimonBurgess** [comment]
Great news. Where is this exposed? Anychane the documentation can include events? Such as a user selects an item. Basic stuff any developer will need really, but it's too hard to find this stuff without reverse engineering it. https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/inputs/combo/overview
